name: Build and Push Docker Image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buildAndPushDockerImage:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        platforms: linux/arm64, linux/amd64
        tags:
          ghcr.io/${{ github.repository }}:latest

